---- CH2. NOTEBOOK
---- Basic Aggregate functions ----
SELECT
	COUNT(*),
	MIN(SALARY),
	MAX(SALARY)
FROM
	DATA_SCI.EMPLOYEES
WHERE
	REGION_ID = 2

	------ Some Statistical aggregate Functions ---
SELECT
	DEPARTMENT_ID,
	SUM(SALARY),
	ROUND(AVG(SALARY), 2) AS MEAN_SALARY,
	ROUND(VAR_POP(SALARY), 2) AS VARIANCE,
	ROUND(STDDEV_POP(SALARY), 2) AS STD
FROM
	DATA_SCI.EMPLOYEES
GROUP BY
	DEPARTMENT_ID
ORDER BY
	MEAN_SALARY DESC
	-------- Groping and Filtering ---- 
SELECT
	LAST_NAME,
	DEPARTMENT_ID,
	SALARY
FROM
	DATA_SCI.EMPLOYEES
WHERE
	LAST_NAME LIKE 'b%'
SELECT
	LAST_NAME,
	DEPARTMENT_ID,
	SALARY
FROM
	DATA_SCI.EMPLOYEES
WHERE
	LAST_NAME LIKE 'b%d'
	OR SALARY > 100000
SELECT
	DEPARTMENT_ID,
	SUM(SALARY)
FROM
	DATA_SCI.EMPLOYEES
WHERE
	SALARY > 100000
GROUP BY
	DEPARTMENT_ID
ORDER BY
	DEPARTMENT_ID
	----- Joinning and filtering Data -----
SELECT
	E.*,
	CR.REGION_NAME,
	CR.COUNTRY_NAME
FROM
	DATA_SCI.EMPLOYEES E
	JOIN DATA_SCI.COMPANY_REGIONS CR ON E.REGION_ID = CR.ID
WHERE
	CR.COUNTRY_NAME = 'canada' --- search is case sensitive !!!


------ CHALLENGE  --------
SELECT 
	E.LAST_NAME, 
	E.EMAIL, 
	CD.DEPARTMENT_NAME
FROM
	DATA_SCI.EMPLOYEES E
	JOIN DATA_SCI.COMPANY_DEPARTMENTS CD ON E.DEPARTMENT_ID=CD.ID
WHERE
	E.SALARY > 120000

